### ISSUE TITLE
Could not find a part of the path

### ISSUE THREAD

**Issue by digitalfiz** [TimHeinrich/GitRewrite#14]
Trying to just list contributors and I get this error:

```
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\MyProject\objects\pack'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at GitRewrite.IO.PackReader.GetPackFiles(String repositoryPath)
   at GitRewrite.Program.Main(String[] args)
```

**Comment by TimHeinrich** [comment]
Hi, looks like you are in your working tree. Just switch to the .git folder and it should work, reopen if it doesn't!

**Comment by Enyium** [comment]
Please provide an error message that tells the user to specify the `.git` directory itself.
