### ISSUE TITLE
--fix-trees: System.NotImplementedException: The method or operation is not implemented

### ISSUE THREAD

**Issue by dennisbk** [TimHeinrich/GitRewrite#15]
when running with the option --fix-trees, I get the following exception
GitRewrite myrepo --fix-trees
Unhandled exception. System.AggregateException: One or more errors occurred. (The method or operation is not implemented.)
 ---> System.NotImplementedException: The method or operation is not implemented.
   at GitRewrite.IO.PackReader.GetGitObject(ObjectHash hash)
   at GitRewrite.IO.PackReader.GetTree(ObjectHash hash)
   at GitRewrite.GitObjectFactory.ReadTree(String repositoryPath, ObjectHash hash)
   at GitRewrite.Program.HasDefectiveTree(String vcsPath, Commit commit)
   at GitRewrite.Program.<>c__DisplayClass6_0.<FindCommitsWithDuplicateTreeEntries>b__0(Commit commit)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1.MoveNextSlowPath()
   at System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1.MoveNext()
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   at GitRewrite.Program.FindCommitsWithDuplicateTreeEntries(String vcsPath)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GitRewrite.Program.Main(String[] args)

**Comment by TimHeinrich** [comment]
Hi, most likely your pack file contains a kind of diff that I did not implement yet (OBJ_REF_DELTA), as I have yet to find a repository where these diffs are used. Is there any chance that I could get access to the repository? While it should be fairly easy to implement, I really would not like to do so without a repo I can test against.

**Comment by dennisbk** [comment]
I don’t think my employer would like me giving out access to the repository. I could put it in debug mode and try to see what’s wrong and send you some more information. If I get some time this week, I’ll give it a try.
Thanks,
Dennis

Dennis Kennedy
Senior Software Engineer
MiCROTEC Inc.

155 SW Madison Ave
Corvallis, OR 97333, USA
T +1 541 753 5111
microtec.us

This e-mail, including attachments, may contain confidential information, which may be protected by legal privilege.
If you perceive not to be the intended recipient, please notify us immediately. Thank you.

**Comment by gyurix** [comment]
@dennisbk Try to do `git gc` and then rerun the `gitrewrite` command, doing that resolved this issue for me.

**Comment by dennisbk** [comment]
Finally getting back to this. I grabbed the latest code and am no longer getting the exception. However, now it doesn't remove any of my duplicate entries.

**Comment by dennisbk** [comment]
git fsck --full returns a couple of dozen duplicate file entries. git gc runs clean and GitRewrite doesn't find any duplicate entries in the debugger.

**Comment by TimHeinrich** [comment]
Ok, seems strange that it does not find them. Can you have a look at the tree with the duplicate entry and maybe post it here (manually anonymized if needed)? Maybe one of my assumptions about trees is wrong. You can see the tree by doing a `git cat-file -p _treehash_` (git fsck should give you the hash). Also feel free to debug it, the method that checks for duplicates is in Tree.cs: HasDuplicateLines
